### ISSUE TITLE
Initial Todo

### ISSUE THREAD

**Issue by wcampbell0x2a** [wcampbell0x2a/heretek#5]
- [x] Resolve addr ptr
- [ ] Resolve register is string (stack string)
- [ ] Resolve c++/rust function names (c++: https://crates.io/crates/cpp_demangle)
- [x] Print StreamOutput
- [ ] Print AsyncRecord result, maybe only when signal occurred?
- [x] use $pc for PC to keep cross-platform solutions
- [x] use $sp for PC to keep cross-platform solutions
- [x] Static registers for most arches? Unsupported ones can just use what gdb returns?
- [x] Move titles over a bit for the ones without full borders
- [ ] Keep cmd history around in a .heretek_history file and load on restart
- [x] Reset UI on ExecResult("running")?
- [x] Make the strings (such as ExecResult("running")), with an enum for "running"
- [x] Color code Heap, Stack, Code, String
- [ ] External control of Input through our own TCP stream
- [ ] Show `breakpoint-hit` in Status or something
- [x] Show function+offset in Instructions (like gef)
- [x] Optional, show bytes of instructions
- [x] Limit Registers to 64 registers?
- [x] Ayu color scheme (maybe theme support, but that's future)
